### ISSUE TITLE
Will not recognize my user

### ISSUE THREAD

**Issue by vongohren** [ptbrowne/whispersync-lib#9]
Hey, first of all, a really nice reverse engineer! Resonated totally with your ingress of the blog: https://ptbrowne.github.io/posts/whispersync-reverse-engineering/

I wanted to play with this for a bit and see what I could do.
So I started registering a device
But the first issue i hit is this:

`<error><customer_not_found>No customer found for this e-mail address and password.</customer_not_found></error>`

I am using the right email and password as envs, and I test that the right values are there. But uncertain why this is happening. I am able to login to https://www.amazon.com/ and it works fine. 
I tried loggin into: https://www.amazon.co.uk/ and that works fine.

So just unsure why it responds like that. Does it work for you now? Or has something changed?

I did some wiresharking and fiddler to check that my app is still calling the same url used in your code, and it seems like it does. The IP changes from time to time though, but doesn change anything to the response.

If you have any thought on why this is happening, I would love a discussion on it

**Comment by vongohren** [comment]
First hinder is passed, it did not like that i had * in my passwords. So got a new password with only lower and upper case

**Comment by ptbrowne** [comment]
Mmh OK, I am glad that I did not have any stars in my password when I reversed engineer then. I will add a warning in the readme. Thanks for the warm words, I am really glad that someone else found this repo useful !

**Comment by monalisir** [comment]
@ptbrowne @vongohren Sorry for this closed issue. I also got <error><customer_not_found>No customer found for this e-mail address and password.</customer_not_found></error>
When I Sign in. Could you tell me what's the version of the app and which device(Android/iOS) you used? 
Can I try it on my Kindle Paperwhite device? But it can not config the proxy. ;(. It's clear that there is no Star* in my password. Thanks.

**Comment by vongohren** [comment]
Unfortunately, I cannot remember @monalisir. But I dont know if that matters.
Its just not star, that is the problem, probably alot of different characters, so be mindful of that aswell
